version: '3.8'

services:
  mongo:
    image: mongo:latest
    command: mongod --auth
    ports:
      - '27019:27017'
    env_file:
      - .env
    volumes: 
      - mongodbdata:/data/db
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27019/
  api:
    build: 
      context: ./
      dockerfile: Dockerfile
    # command: npm run start:dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
volumes:
  mongodbdata:
    driver: local